import {
  LayoutDashboard, SlidersHorizontal, BarChart3, FileText, BookOpen,
  Trophy, Settings as SettingsIcon, Play, Headphones, Star, TrendingUp,
  ShieldAlert, Bot, Keyboard, History, Brain, MessageSquare,
  Medal, Ticket, Crown, Mail,
} from 'lucide-react'

export const icons = {
  LayoutDashboard,
  SlidersHorizontal,
  BarChart3,
  FileText,
  BookOpen,
  Trophy,
  Settings: SettingsIcon,
  Play,
  Headphones,
  Star,
  TrendingUp,
  ShieldAlert,
  Bot,
  Keyboard,
  History,
  Brain,
  MessageSquare,
  Medal,
  Ticket,
  Crown,
  Mail,
}
